# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('alias', models.SlugField(verbose_name='Alias категории')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('alias', models.SlugField(verbose_name='Alias товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('order_total', models.IntegerField(null=True)),
                ('payment', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('item_price', models.IntegerField(default=0, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Order')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255, null=True, verbose_name='Название ресторана')),
            ],
            options={
                'verbose_name': 'Название ресторана',
                'verbose_name_plural': 'Названия ресторанов',
            },
        ),
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter_name', models.CharField(max_length=255, null=True, verbose_name='Имя официанта')),
                ('work_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.OrderPlace', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Имя официанта',
                'verbose_name_plural': 'Имена официантов',
            },
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='hello.OrderLine', to='hello.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.OrderPlace'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Waiters'),
        ),
    ]
